export default {
  MARK_NOTIFICATION_AS_READ: 'MARK_NOTIFICATION_AS_READ',
  MARK_ALL_NOTIFICATION_AS_READ: 'MARK_ALL_NOTIFICATION_AS_READ',
  START_LOADING: 'START_LOADING',
  FINISH_LOADING: 'FINISH_LOADING',
  RECIVED_NOTIFICATIONS: 'RECIVED_NOTIFICATIONS'
}
